version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: education_platform_db
    environment:
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234}
      POSTGRES_DB: ${DB_NAME:-education_platform}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - education_network

  # Redis for Math Service (Celery)
  redis:
    image: redis:7-alpine
    container_name: education_platform_redis
    ports:
      - "6379:6379"
    networks:
      - education_network

  # Math Service
  math-service:
    build:
      context: ./services/math-service
      dockerfile: Dockerfile
    container_name: math_service
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-password}@postgres:5432/${DB_NAME:-education_platform}
      - REDIS_URL=redis://redis:6379/0
      - GEMINI_API_KEY=${MATH_GEMINI_API_KEY:-${GEMINI_API_KEY}}
      - GOOGLE_VISION_API_KEY=${GOOGLE_VISION_API_KEY}
      - PORT=8000
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./services/math-service:/app
    networks:
      - education_network
    restart: unless-stopped

  # English Service
  english-service:
    build:
      context: ./services/english-service
      dockerfile: Dockerfile
    container_name: english_service
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-password}@postgres:5432/${DB_NAME:-education_platform}
      - GEMINI_API_KEY=${ENGLISH_GEMINI_API_KEY:-${GEMINI_API_KEY}}
      - PORT=8000
    ports:
      - "8002:8000"
    depends_on:
      - postgres
    volumes:
      - ./services/english-service:/app
    networks:
      - education_network
    restart: unless-stopped

  # Celery Worker for Math Service
  celery-worker:
    build:
      context: ./services/math-service
      dockerfile: Dockerfile.celery
    container_name: math_celery_worker
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-password}@postgres:5432/${DB_NAME:-education_platform}
      - REDIS_URL=redis://redis:6379/0
      - GEMINI_API_KEY=${MATH_GEMINI_API_KEY:-${GEMINI_API_KEY}}
      - GOOGLE_VISION_API_KEY=${GOOGLE_VISION_API_KEY}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./services/math-service:/app
    networks:
      - education_network
    restart: unless-stopped

  # Flower for Celery Monitoring
  flower:
    build:
      context: ./services/math-service
      dockerfile: Dockerfile.celery
    container_name: math_flower
    command: celery -A app.celery_app flower
    environment:
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis
    networks:
      - education_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  education_network:
    driver: bridge