version: '3.8'

services:
  korean-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./data:/app/data
      - ./korean_problems.db:/app/korean_problems.db
    networks:
      - korean-service-network

  korean-celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./data:/app/data
      - ./korean_problems.db:/app/korean_problems.db
    networks:
      - korean-service-network

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    networks:
      - korean-service-network

networks:
  korean-service-network:
    driver: bridge